import raw from './github.json'

/**
 * Typed view over the build-time GitHub snapshot.
 *
 * The JSON is generated by scripts/fetch-github.mjs and is committed, so the
 * site still builds when the API is unreachable. When it has never been
 * fetched the arrays are empty, and TypeScript would otherwise infer those as
 * `never[]`, which is why the shape is declared here rather than inferred.
 */

export type Language = {
  name: string
  count: number
  share: number
}

export type Repo = {
  name: string
  url: string
  description: string | null
  language: string | null
  stars: number
  pushedAt: string
}

export type GithubSnapshot = {
  user: {
    login: string
    url: string
    publicRepos: number
    followers: number
  } | null
  languages: Language[]
  recent: Repo[]
  fetchedAt: string | null
}

export const github = raw as GithubSnapshot
